# Default local configuration
dumpPropertiesOnStartup: true
enableConsoleOutput: true

jdbc:
  driver: com.mysql.jdbc.Driver
  url: jdbc:mysql://localhost:3306/sales_tax
  user: sales_tax_ro
  password: Zusse877

# "unit-test" Profile
---
spring:
  profiles: unit-test

jdbc:
  driver: org.h2.Driver
  url: jdbc:h2:mem:salestax;DB_CLOSE_DELAY=-1;MVCC=true;DB_CLOSE_ON_EXIT=TRUE;LOCK_TIMEOUT=10000
  user: 
  password: 
